# Generated by Django 4.0.6 on 2022-08-02 08:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
        ('stays', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'book_status',
            },
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('book_number', models.CharField(max_length=45)),
                ('checkin', models.DateField()),
                ('checkout', models.DateField()),
                ('room_option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stays.roomoption')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.bookstatus')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.user')),
            ],
            options={
                'db_table': 'books',
            },
        ),
    ]
