# Generated by Django 4.0.6 on 2022-08-03 02:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='checkin',
            new_name='check_in',
        ),
        migrations.RenameField(
            model_name='book',
            old_name='checkout',
            new_name='check_out',
        ),
        migrations.AlterModelTable(
            name='bookstatus',
            table='book_statuses',
        ),
    ]
