# Generated by Django 4.0.6 on 2022-08-06 08:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stays', '0002_alter_stay_latitude_alter_stay_longitude'),
        ('books', '0002_rename_checkin_book_check_in_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='room_option',
        ),
        migrations.AddField(
            model_name='book',
            name='room',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='stays.room'),
            preserve_default=False,
        ),
    ]
