# Generated by Django 4.0.6 on 2022-08-02 08:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Option',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('season', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'options',
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=45)),
                ('content', models.CharField(max_length=400)),
                ('max_capacity', models.IntegerField()),
                ('min_capacity', models.IntegerField()),
                ('checkout', models.CharField(max_length=45)),
                ('checkin', models.CharField(max_length=45)),
                ('area', models.DecimalField(decimal_places=2, max_digits=15)),
                ('bed', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'rooms',
            },
        ),
        migrations.CreateModel(
            name='RoomType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'room_type',
            },
        ),
        migrations.CreateModel(
            name='Stay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=45)),
                ('address', models.CharField(max_length=200)),
                ('latitude', models.CharField(max_length=45)),
                ('longitude', models.CharField(max_length=45)),
                ('keyword', models.CharField(max_length=45)),
                ('summary', models.CharField(max_length=200)),
                ('content_top', models.TextField(max_length=200)),
                ('content_bottom', models.TextField(max_length=200)),
                ('phone_number', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'stays',
            },
        ),
        migrations.CreateModel(
            name='StayType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'stay_type',
            },
        ),
        migrations.CreateModel(
            name='Theme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45)),
                ('icon', models.CharField(max_length=45)),
                ('detail', models.CharField(max_length=200)),
                ('stay', models.ManyToManyField(related_name='themes', to='stays.stay')),
            ],
            options={
                'db_table': 'themes',
            },
        ),
        migrations.CreateModel(
            name='StayImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.CharField(max_length=400)),
                ('stay', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stays.stay')),
            ],
            options={
                'db_table': 'stay_images',
            },
        ),
        migrations.AddField(
            model_name='stay',
            name='stay_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stays.staytype'),
        ),
        migrations.CreateModel(
            name='RoomOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=15)),
                ('option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stays.option')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stays.room')),
            ],
            options={
                'db_table': 'room_options',
            },
        ),
        migrations.CreateModel(
            name='RoomImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.CharField(max_length=400)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stays.room')),
            ],
            options={
                'db_table': 'room_images',
            },
        ),
        migrations.AddField(
            model_name='room',
            name='room_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stays.roomtype'),
        ),
        migrations.AddField(
            model_name='room',
            name='stay',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stays.stay'),
        ),
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45)),
                ('icon', models.CharField(max_length=200)),
                ('room', models.ManyToManyField(related_name='features', to='stays.room')),
            ],
            options={
                'db_table': 'features',
            },
        ),
        migrations.CreateModel(
            name='Amenity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45)),
                ('room', models.ManyToManyField(related_name='amenities', to='stays.room')),
            ],
            options={
                'db_table': 'amenities',
            },
        ),
        migrations.CreateModel(
            name='AddOn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45)),
                ('room', models.ManyToManyField(related_name='add_ons', to='stays.room')),
            ],
            options={
                'db_table': 'add_ons',
            },
        ),
    ]
