# Generated by Django 4.0.6 on 2022-08-03 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stays', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stay',
            name='latitude',
            field=models.DecimalField(decimal_places=10, max_digits=20),
        ),
        migrations.AlterField(
            model_name='stay',
            name='longitude',
            field=models.DecimalField(decimal_places=10, max_digits=20),
        ),
    ]
