# Generated by Django 4.0.6 on 2022-08-03 04:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stays', '0002_alter_stay_latitude_alter_stay_longitude'),
        ('likes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='like',
            name='room_option',
        ),
        migrations.AddField(
            model_name='like',
            name='stay',
            field=models.ForeignKey(default={}, on_delete=django.db.models.deletion.CASCADE, to='stays.stay'),
            preserve_default=False,
        ),
    ]
